### ISSUE TITLE
Crash when pressing 'Fix 2' in Simulation mode.

### ISSUE THREAD

**Issue by filcole** [MscrmTools/MscrmTools.SolutionTableIntegrityManager#2]
Hi, Trying out the 'Solution Table Integrity Manager' and I got a crash when pressing 'Apply this fix' (option 2) in simulation mode.

![image](https://github.com/MscrmTools/MscrmTools.SolutionTableIntegrityManager/assets/6078398/97d14726-1344-4ee8-a103-fd3f6137a543)

```text
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MscrmTools.SolutionTableIntegrityManager.PluginControl.fixControl_Apply(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)



```

**Comment by MscrmTools** [comment]
It seems the error occurred before really working... I will double check what might be wrong.
Anything special with the selected table?

**Comment by MscrmTools** [comment]
Can you try one thing? Before clicking on the action, ensure the solution is selected in the left solution list?

I cannot see for now other object that might be null

And is there a progress dialog shown before the error?

**Comment by MscrmTools** [comment]
@filcole can you check with latest version if you still have the issue?
